#! $HOME/SOFTWARE/anaconda2/envs/vison/bin/ python


# IMPORT STUFF
import sys, os
from optparse import OptionParser
from vison.eyegore.eyegore import Eyegore,_extpath
from vison.support import context
# END IMPORT


if __name__ == '__main__':
    
    parser = OptionParser()
    parser.add_option("-p","--path",dest="path",default='',help="day-path to be monitored.")
    parser.add_option("-B","--broadcast",dest="broadcast",action='store_true',default=False,help="Synchronize data to gateway folder: %s" % _extpath)
    parser.add_option("-E","--elvis",dest="elvis",default=context.elvis,help="ELVIS version.")
    parser.add_option("-L","--lite",dest="lite",action="store_true",default=False,help="Run a lighter version of the program (no autom. HK-plots or image displays).")
    parser.add_option("-r","--rsync",dest="altpath",default='',help="rsync to an alternative local path.")
    
    (options, args) = parser.parse_args()
    
    if options.path == '':
        parser.print_help()
        sys.exit()
        
    path = options.path
    broadcast = bool(options.broadcast)
    elvis = options.elvis
    altpath = options.altpath
    dolite = bool(options.lite)
    
    if not os.path.exists(path):
        sys.exit('HKmonitory.py: %s does not exist' % path)
    else:
        
        header = '\n\n#########################################################\n'+\
                 '#                                                       #\n'+\
                 '#                                                       #\n'+\
                 '#       starting EYEGORE on path:                        #\n'+\
                 '            %s                                           \n'+\
                 '#                                                       #\n'+\
                 '#                                                       #\n'+\
                 '#########################################################\n'
        
        print header % path
    
    
    app = Eyegore(path,broadcast=broadcast,elvis=elvis,dolite=dolite,altpath=altpath)

